---
# tasks file for roles/ansible-sbt

# echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
# sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
# sudo apt-get update
# sudo apt-get install sbt

- name: Determine whether to use sudo for package installations
  set_fact:
    should_become: "{{ ansible_env.ANSIBLE_CONTAINER is not defined }}"

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: 'Install SBT package'
  become: "{{ should_become }}"
  package:
    name: sbt
    state: latest

- name: Cleanup package caches if building a container
  include: cleanup.yml
  when: ansible_env.ANSIBLE_CONTAINER is defined